__author__ = 'colmh'

'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
'''
'''
take first and second number
store second num in temp
add them and assign to second number
assign temp to first number
loop
'''

first = 0
second = 1
total = 0

while second < 4000000:
    swap = second
    second += first
    first = swap
    #print ("[{0}], [{1}]".format(first, second))
    temp = first + second
    if 0 == temp % 2:
        total += temp

print total

